version: '3'

services:
  buddies-react-fe:
    container_name: buddies-react-fe
    image: react-fe:latest
    restart: always
    ports:
      - 7700:5173
    logging:
      driver: "json-file"
      options:
        max-size: "300m" 
        max-file: "5"
    volumes:
      - ./logs:/var/log/app